const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const HOST="127.0.0.1",PORT=Number(process.env.PORT||5500),ROOT=__dirname,PASSWORD=process.env.BLOSSOM_PASSWORD;
if(!PASSWORD){console.error('\nSet a password first:\n$env:BLOSSOM_PASSWORD="your-long-private-password"\nThen run: node server.js\n');process.exit(1)}
const TTL=7*24*60*60*1000,sessions=new Map(),attempts=new Map();
const LOGIN=`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive,noimageindex"><title>Private Garden</title><style>
*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;background:radial-gradient(circle at 50% 30%,#3b0718,#120107 42%,#000 85%);color:#fff;font-family:Georgia,serif}.card{width:min(90vw,420px);padding:42px 28px;text-align:center;border:1px solid #5c2437;border-radius:24px;background:#090005e8;box-shadow:0 25px 80px #000}.flower{font-size:44px}.tag{font:11px Arial;letter-spacing:.22em;color:#e7a0b5;margin:14px}h1{font-weight:400;font-size:34px;margin:8px 0 12px}p{color:#d3b2bc;line-height:1.6;font-size:14px}input,button{width:100%;padding:15px;border-radius:14px;font-size:16px}input{margin-top:10px;background:#120109;color:#fff;border:1px solid #633047;text-align:center;outline:0}button{margin-top:12px;border:0;color:#fff;font-weight:700;background:linear-gradient(135deg,#971139,#d42b60);cursor:pointer}#e{min-height:20px;color:#ff9ab7;font:13px Arial;margin-top:13px}.small{font:11px Arial;color:#775863}</style></head><body><main class="card"><div class="flower">🌸</div><div class="tag">PRIVATE GARDEN</div><h1>Something special is waiting.</h1><p>This little place was made for one special visitor.<br>Enter the password to continue.</p><form id="f"><input id="p" type="password" autocomplete="current-password" placeholder="Enter password" required maxlength="128"><button>Unlock the garden ♡</button><div id="e"></div></form><p class="small">Private access • Please don't share the link or password</p></main><script>
f.onsubmit=async x=>{x.preventDefault();e.textContent="Checking…";try{let r=await fetch("/__login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:p.value})});if(r.ok)return location.replace("/");let j=await r.json().catch(()=>({}));e.textContent=j.error||"That password didn't work."}catch(_){e.textContent="Couldn't connect. Please try again."}};
</script></body></html>`;
function headers(res){res.setHeader("X-Content-Type-Options","nosniff");res.setHeader("Referrer-Policy","no-referrer");res.setHeader("X-Robots-Tag","noindex, nofollow, noarchive, nosnippet, noimageindex");res.setHeader("Permissions-Policy","camera=(), microphone=(), geolocation=()");res.setHeader("Cache-Control","private, no-store");res.setHeader("Content-Security-Policy","default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; font-src 'self' data:; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'")}
function send(res,s,b,t="text/html; charset=utf-8"){headers(res);res.writeHead(s,{"Content-Type":t});res.end(b)}
function ck(req){let o={};for(let q of(req.headers.cookie||"").split(";")){let i=q.indexOf("=");if(i>0)o[q.slice(0,i).trim()]=decodeURIComponent(q.slice(i+1).trim())}return o}
function auth(req){let t=ck(req).blossom_session,x=t&&sessions.get(t);if(!x||x<=Date.now()){if(t)sessions.delete(t);return false}return true}
function eq(a,b){a=Buffer.from(String(a));b=Buffer.from(String(b));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function ip(req){return String(req.headers["x-forwarded-for"]||req.socket.remoteAddress||"unknown").split(",")[0].trim()}
function mime(f){return({".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript; charset=utf-8",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png",".webp":"image/webp",".svg":"image/svg+xml",".mp3":"audio/mpeg",".m4a":"audio/mp4",".wav":"audio/wav"})[path.extname(f).toLowerCase()]||"application/octet-stream"}
setInterval(()=>{let n=Date.now();for(let[t,x]of sessions)if(x<=n)sessions.delete(t);for(let[i,x]of attempts)if(n-x.start>900000)attempts.delete(i)},600000).unref();
http.createServer((req,res)=>{
 headers(res);
 if(req.url==="/__login"&&req.method==="POST"){let k=ip(req),n=Date.now(),a=attempts.get(k)||{count:0,start:n};if(n-a.start>900000)a={count:0,start:n};if(a.count>=10)return send(res,429,JSON.stringify({error:"Too many attempts. Try again later."}),"application/json");let body="";req.on("data",c=>{body+=c;if(body.length>4096)req.destroy()});req.on("end",()=>{let supplied="";try{supplied=JSON.parse(body).password||""}catch{}if(!eq(supplied,PASSWORD)){a.count++;attempts.set(k,a);return send(res,401,JSON.stringify({error:"That password didn't work."}),"application/json")}attempts.delete(k);let token=crypto.randomBytes(32).toString("hex");sessions.set(token,Date.now()+TTL);res.setHeader("Set-Cookie",`blossom_session=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.floor(TTL/1000)}`);send(res,200,'{"ok":true}',"application/json")});return}
 if(!auth(req))return send(res,200,LOGIN);
 let pn;try{pn=decodeURIComponent(new URL(req.url,"http://local").pathname)}catch{return send(res,400,"Bad request","text/plain")}
 if(pn==="/")pn="/index.html";let f=path.resolve(ROOT,pn.replace(/^\/+/,""));if(f!==ROOT&&!f.startsWith(ROOT+path.sep))return send(res,403,"Forbidden","text/plain");
 fs.stat(f,(er,st)=>{if(er||!st.isFile())return send(res,404,"Not found","text/plain");headers(res);res.writeHead(200,{"Content-Type":mime(f)});fs.createReadStream(f).pipe(res)})
}).listen(PORT,HOST,()=>console.log(`\n🌸 Private server: http://${HOST}:${PORT}\n🔐 Password gate: ON\n🍪 Session: 7 days (until server restart)\nKeep this terminal open.\n`));